config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root'pages#index'
  post'newsletter', to: 'newsletter#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/newsletter.rb
class Newsletter
  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :email

  validates :email,
            presence: { message: "Kérjük adja meg email címét" }
  validates_format_of :email, :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/, :message => "Kérjük valós email címet adjon meg"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/newsletter_controller.rb
class NewsletterController < ApplicationController
	require 'rest-client'

	def new
    	@newsletter = Newsletter.new
  	end

  	def create
  		@newsletter = Newsletter.new(newsletter_params)
  		
  		respond_to do |format|


	  		format.js do 
	  			if @newsletter.valid?

	  				api_key = ENV['SENDGRID_API_KEY']
					headers = {'Authorization' => "Bearer #{api_key}"}
					mail = @newsletter.email
					data = {:email => mail }

					reset = RestClient.delete "https://api.sendgrid.com/v3/asm/groups/3365/suppressions/#{mail}", headers
					response = RestClient.post 'https://api.sendgrid.com/v3/contactdb/recipients', [data].to_json, headers
					
					flash.now[:notice] = "köszönjük hogy feliratkozott az alábbi címmel: #{mail}"
	  			else
          			flash.now[:error]
	  			end
	  		end

  		end

  	end

  	private

  	def newsletter_params
    params.require(:newsletter).permit( :email)
  	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splatcrewseu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/newsletter/create.js.erb
<% if flash[:notice] %>

$('#new_newsletter').after('<div class="notice row"><%= flash[:notice] %></div>');
$('#errors').remove();
$('#new_newsletter').remove();
$('.notice').click(function(){
    $(this).remove();
});

<% end %>

<% if @newsletter.errors.any? %>

$('#errors').remove();
$('#newsletter_email').after('<div class="errors row" id="errors"><% @newsletter.errors.each do |attr,msg| %><%= msg %><br><% end %></div>');
var newsletterformwidth = $('#new_newsletter').width();
$('.errors').width(newsletterformwidth);
$('.errors').click(function(){
    $(this).remove();
});

<% end %>

app/views/pages/_newsletter.html.erb
<%= form_for Newsletter.new, html: { remote: true }, url: newsletter_path do |newsletter_form| %>

	<%= newsletter_form.text_field :email, placeholder: "Email", class: "form-control" %>
	</br>
	<%= newsletter_form.submit "feliratkozás", class: "btn btn-default btn-lg", id: "btn" %>

<% end %>

app/views/pages/index.html.erb
<%= render'pages/newsletter' %>